### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by 7177981** [SistemasTecTlaxiaco/mapa-mental-7177981#2]
[SAMUEL HOYOS MORA MAPA MENTAL-MD.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-7177981/files/7334731/SAMUEL.HOYOS.MORA.MAPA.MENTAL-MD.pdf)

**Comment by irving1613** [comment]
La informacion es buena, pero falta diseño y fuentes.
**Calificacion: 82**

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
